Repository appuio/appuio-cloud-reporting, pull requests merged in 2022-05, with the labels that each got.

#55 Add support for sub queries
  pkg/db/migrations/0012_sub_query.sql
  pkg/db/types.go
  pkg/invoice/invoice.go
  pkg/invoice/invoice_test.go
  pkg/report/report.go
  pkg/report/report_test.go
Labels: enhancement

#58 Do not expose DB IDs in the invoice
  pkg/invoice/invoice.go
  pkg/invoice/invoice_test.go
Labels: ignore

#57 Add golden tests for creating invoices
  Makefile
  pkg/db/types.go
  pkg/db/types_test.go
  pkg/invoice/invoice_golden_discounts_test.go
  pkg/invoice/invoice_golden_products_test.go
  pkg/invoice/invoice_golden_simple_test.go
  pkg/invoice/invoice_golden_test.go
  pkg/invoice/invoice_golden_timed_discounts_test.go
  pkg/invoice/invoice_golden_timed_query_test.go
  pkg/invoice/invoice_test.go
  pkg/invoice/main_test.go
  pkg/invoice/testdata/discounts.json
  pkg/invoice/testdata/products.json
  pkg/invoice/testdata/simple.json
  pkg/invoice/testdata/timed_discounts.json
  pkg/invoice/testdata/timed_query.json
Labels: change

#56 Add subqueries for memory query
  go.mod
  go.sum
  pkg/db/seeds.go
  pkg/db/seeds/appuio_cloud_memory_sub_cpu.promql
  pkg/db/seeds/appuio_cloud_memory_sub_memory.promql
  pkg/db/seeds_test.go
  pkg/db/types.go
Labels: enhancement

#64 Expose the query name for every invoice line item
  pkg/invoice/invoice.go
  pkg/invoice/invoice_test.go
  pkg/invoice/testdata/discounts.json
  pkg/invoice/testdata/products.json
  pkg/invoice/testdata/simple.json
  pkg/invoice/testdata/timed_discounts.json
  pkg/invoice/testdata/timed_query.json
Labels: enhancement

#46 Factor CPU requests into APPUiO Cloud Memory
  pkg/db/seeds/appuio_cloud_memory.promql
Labels: change

#66 Return subitems in invoices as a map
  pkg/invoice/invoice.go
  pkg/invoice/invoice_test.go
  pkg/invoice/main_test.go
  pkg/invoice/testdata/discounts.json
  pkg/invoice/testdata/products.json
  pkg/invoice/testdata/simple.json
  pkg/invoice/testdata/timed_discounts.json
  pkg/invoice/testdata/timed_query.json
Labels: ignore

#67 Only count CPU and memory requests of running pods
  pkg/db/seeds/appuio_cloud_memory.promql
  pkg/db/seeds/appuio_cloud_memory_sub_cpu.promql
  pkg/db/seeds/appuio_cloud_memory_sub_memory.promql
Labels: bug

#70 Show only extra paid requests
  pkg/db/seeds.go
  pkg/db/seeds/appuio_cloud_memory_sub_memory.promql
Labels: change
