Repository appuio/appuio-cloud-reporting, pull requests merged in 2022-01, with the labels that each got.

#7 Create temporary DB for each database test suite. Add testing how-to to Readme.
  Readme.md
  go.mod
  go.sum
  pkg/db/dbtest/suite.go
  pkg/db/dbtest/suite_test.go
Labels: change

#6 Query Metrics and Save in Fact
  .gitignore
  Makefile
  Makefile.vars.mk
  README.md
  common_flags.go
  go.mod
  go.sum
  kind/config.yaml
  kind/kind.mk
  main.go
  migrate_command.go
  pkg/db/dbtest/suite.go
  pkg/db/migrations.go
  pkg/db/open.go
  pkg/db/seeds.go
  pkg/db/seeds/appuio_cloud_loadbalancer.promql
  pkg/db/seeds/appuio_cloud_memory.promql
  pkg/db/seeds/appuio_cloud_persistent_storage.promql
  pkg/db/seeds/ping.promql
  pkg/db/seeds_test.go
  pkg/db/util.go
  pkg/report/report.go
  pkg/report/report_test.go
  pkg/sourcekey/sourcekey.go
  pkg/sourcekey/sourcekey_test.go
  pkg/testsuite/prometheus.go
  pkg/testsuite/testsuite.go
  pkg/testsuite/testsuite_test.go
  report_command.go
  testreport_command.go
  tools.go
  util/ensure_prometheus/main.go
Labels: enhancement

#12 Exit with error only if migrations are pending
  migrate_command.go
Labels: enhancement

#11 Download prometheus using make instead of Go
  Makefile
  Makefile.vars.mk
  README.md
  go.mod
  go.sum
  pkg/testsuite/prometheus.go
  pkg/testsuite/testsuite.go
  util/ensure_prometheus/main.go
Labels: change

#17 Make upsert non-row-locking
  pkg/report/report.go
  pkg/report/report_test.go
Labels: enhancement

#16 Allow querying ranges
  logger.go
  main.go
  migrate_command.go
  pkg/db/seeds/appuio_cloud_memory.promql
  pkg/db/seeds/appuio_cloud_persistent_storage.promql
  pkg/report/report.go
  pkg/report/report_test.go
  report_command.go
Labels: enhancement

#10 Add docker compose setup for local testing
  Makefile
  Makefile.compose.mk
  Makefile.vars.mk
  README.md
  docker-compose-test.yml
  docker-compose.yml
Labels: change

#19 Prepare simple Grafana deployment
  .gitignore
  README.md
  manifests/grafana/Makefile
  manifests/grafana/grafana-helm-values.yaml
Labels: enhancement

#21 Remove 'ping' query seed
  pkg/db/seeds.go
  pkg/db/seeds/ping.promql
Labels: change

#15 Invoice MVP
  invoice_command.go
  main.go
  pkg/db/migrations/0011_discounts_discount_to_float64.sql
  pkg/db/schema_test.go
  pkg/db/types.go
  pkg/db/types_test.go
  pkg/db/util.go
  pkg/db/util_test.go
  pkg/invoice/invoice.go
  pkg/invoice/invoice_test.go
  pkg/report/report.go
  pkg/report/report_test.go
Labels: enhancement

#23 Fix PromQL join on persistent storage
  pkg/db/seeds/appuio_cloud_persistent_storage.promql
Labels: bug

#24 Document source key usage
  pkg/db/types.go
Labels: documentation

#25 Define adapter interface
  pkg/erp/adapter.go
  pkg/erp/category.go
  pkg/erp/entity/category.go
Labels: change

#27 Add category reconciler
  pkg/categories/category.go
  pkg/categories/category_test.go
  pkg/db/dbtest/suite.go
  pkg/db/util.go
  pkg/erp/adapter.go
  pkg/report/report.go
Labels: enhancement

#26 Add required invoice metadata for Odoo
  invoice_command.go
  pkg/invoice/invoice.go
  pkg/invoice/invoice_test.go
Labels: enhancement
